### ISSUE TITLE
建议在你的 README.md 里添加你的 bilibili 讲解链接。

### ISSUE THREAD

**Issue by Howard07** [kivvi3412/HandWrite#3]
建议在你的 README.md 里添加你的 bilibili 讲解链接：[开源了个手写字生成器解决大学生无用的手写作业](https://www.bilibili.com/video/BV1324y1P7pV/?share_source=copy_web&vd_source=8f4728ca528c4f3b362697c9193278ff)

**Comment by kivvi3412** [comment]
已添加
